// Registers the PWA service worker generated by vite-plugin-pwa
// Minimal setup for now; update prompts will be added later.
import { registerSW } from 'virtual:pwa-register'

registerSW({
  immediate: true,
})

